export const usuarios=[
    {
        nombre:'usuario1',
        psw:'1234',
        arregloFicheros:[
            {
                nombre:'/',
                carpetas:[]
            },
            {
                nombre:'/var',
                carpetas:[]
            },
            {
                nombre:'/tmp',
                carpetas:[]
            },
            {
                nombre:'/home',
                carpetas:[]
            },
            {
                nombre:'/home/user',
                carpetas:[]
            },
            {
                nombre:'/home/user/docs',
                carpetas:[]
            },

        ]
    },
    {
        nombre:'usuario2',
        psw:'1234',
        arregloFicheros:[
            {
                nombre:'/',
                carpetas:[]
            },
            {
                nombre:'/var',
                carpetas:[]
            },
            {
                nombre:'/tmp',
                carpetas:[]
            },
            {
                nombre:'/home',
                carpetas:[]
            },
            {
                nombre:'/home/user',
                carpetas:[]
            },
            {
                nombre:'/user/docs',
                carpetas:[]
            },

        ]
    },
    {
        nombre:'usuario3',
        psw:'1234',
        arregloFicheros:[
            {
                nombre:'/',
                carpetas:[]
            },
            {
                nombre:'/var',
                carpetas:[]
            },
            {
                nombre:'/tmp',
                carpetas:[]
            },
            {
                nombre:'/home',
                carpetas:[]
            },
            {
                nombre:'/home/user',
                carpetas:[]
            },
            {
                nombre:'/user/docs',
                carpetas:[]
            },

        ]
    },
] 